name: hash-tool
version: 0.1.0.0
github: 'zkourouma/hash-tool'
license: BSD3
author: 'Zack Kourouma'
maintainer: 'zack@kourouma.me'
copyright: '2019 Zack Kourouma'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/zkourouma/hash-tool#readme>

dependencies:
  - base >= 4.7 && < 5
  - pureMD5
  - optparse-applicative

library:
  source-dirs: src
  dependencies:
    - bytestring
  exposed-modules:
    - Hashing
    - CliParser

executables:
  hash-tool:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hash-tool

tests:
  hash-tool-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hash-tool
      - hspec
